"""Deterministic continuous simulation primitives for the Web runtime."""

from .adapter import SimulationAdapter
from .engine import (
    DEFAULT_TICK_MS,
    SimulationAction,
    SimulationActionCompletion,
    SimulationEngine,
)
from .models import (
    ActiveSimulationCommand,
    SimulationFrame,
    SimulationRobotState,
    SimulationSensors,
)
from .mission import (
    MissionTaskAccepted,
    MissionTaskCoordinator,
    MissionTaskCancelAccepted,
    MissionTaskRequest,
    MissionTaskResult,
    MissionTaskSnapshot,
    MissionTaskNotActiveError,
    RuntimeCapabilities,
    RuntimeEvent,
)
from .run_gate import RuntimeRunGate, RuntimeRunGateBusyError, RuntimeRunLease
from .semantic import SemanticObjectEvidence, SemanticQueryFilter, SemanticQueryResult, query_semantic_world
from .faults import (
    FaultCoordinator,
    FaultEvidence,
    FaultEvidenceOverflow,
    FaultFinalEvidencePayload,
    FaultObservationEvidencePayload,
    FaultPrepareEvidencePayload,
    FaultPublishedEvidencePayload,
    FaultRunAccepted,
    FaultRunRequest,
    FaultRunSnapshot,
    FaultScenario,
    FaultServiceDisconnectedEvidencePayload,
    FaultServiceRestoredEvidencePayload,
    FaultTimeoutEvidencePayload,
    MqttFaultRunner,
    MAX_FAULT_EVIDENCE,
)
from .mission_runner import (
    RuntimeMissionObserver,
    SimulationMissionRunner,
    execute_operator_emergency_stop,
)
from .world import (
    RobotSpawn,
    SemanticObjectColor,
    SemanticObjectKind,
    WorldBounds,
    WorldConfig,
    WorldGeometry,
    WorldObstacle,
    WorldSemanticObject,
    obstacle_world_config,
    preview_world_config,
)
from .runtime import RuntimeEventHub
from .replay import (
    AcceptanceManifest,
    AcceptanceScenarioResult,
    ReplayBundle,
    ReplayEvidenceInvalid,
    ReplayFrameCapture,
    ReplayFrameSample,
    ReplayRecorder,
    TruthfulnessProfile,
)

__all__ = [
    "ActiveSimulationCommand",
    "DEFAULT_TICK_MS",
    "SimulationAction",
    "SimulationActionCompletion",
    "SimulationAdapter",
    "SimulationEngine",
    "SimulationFrame",
    "SimulationRobotState",
    "SimulationSensors",
    "MissionTaskAccepted",
    "MissionTaskCancelAccepted",
    "MissionTaskCoordinator",
    "MissionTaskRequest",
    "MissionTaskResult",
    "MissionTaskSnapshot",
    "MissionTaskNotActiveError",
    "RuntimeCapabilities",
    "RuntimeEvent",
    "RuntimeEventHub",
    "AcceptanceManifest",
    "AcceptanceScenarioResult",
    "ReplayBundle",
    "ReplayEvidenceInvalid",
    "ReplayFrameCapture",
    "ReplayFrameSample",
    "ReplayRecorder",
    "TruthfulnessProfile",
    "RuntimeRunGate",
    "RuntimeRunGateBusyError",
    "RuntimeRunLease",
    "SemanticObjectEvidence",
    "SemanticQueryFilter",
    "SemanticQueryResult",
    "query_semantic_world",
    "FaultCoordinator",
    "FaultEvidence",
    "FaultEvidenceOverflow",
    "FaultFinalEvidencePayload",
    "FaultObservationEvidencePayload",
    "FaultPrepareEvidencePayload",
    "FaultPublishedEvidencePayload",
    "FaultRunAccepted",
    "FaultRunRequest",
    "FaultRunSnapshot",
    "FaultScenario",
    "FaultServiceDisconnectedEvidencePayload",
    "FaultServiceRestoredEvidencePayload",
    "FaultTimeoutEvidencePayload",
    "MqttFaultRunner",
    "MAX_FAULT_EVIDENCE",
    "RuntimeMissionObserver",
    "SimulationMissionRunner",
    "execute_operator_emergency_stop",
    "RobotSpawn",
    "SemanticObjectColor",
    "SemanticObjectKind",
    "WorldBounds",
    "WorldConfig",
    "WorldGeometry",
    "WorldObstacle",
    "WorldSemanticObject",
    "obstacle_world_config",
    "preview_world_config",
]
